CREATE TABLE "charge_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"data_set_id" integer NOT NULL,
	"data_record_id" integer,
	"charge_type_id" integer,
	"cost" real,
	"units" real,
	"rate" real
);
--> statement-breakpoint
CREATE TABLE "config_charge_types" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contract_charges" (
	"id" serial PRIMARY KEY NOT NULL,
	"contract_id" integer NOT NULL,
	"charge_type_id" integer,
	"rate" real,
	"tolerance" real,
	"tolerance_rate" real,
	"tolerance_units" real
);
--> statement-breakpoint
CREATE TABLE "contract_data" (
	"id" serial PRIMARY KEY NOT NULL,
	"contract_id" integer NOT NULL,
	"type" text,
	"cost_rate" real,
	"time_start" text,
	"time_finish" text,
	"meter" integer,
	"description" text,
	"sunday" boolean DEFAULT true,
	"monday" boolean DEFAULT true,
	"tuesday" boolean DEFAULT true,
	"wednesday" boolean DEFAULT true,
	"thursday" boolean DEFAULT true,
	"friday" boolean DEFAULT true,
	"saturday" boolean DEFAULT true,
	"january" boolean DEFAULT true,
	"february" boolean DEFAULT true,
	"march" boolean DEFAULT true,
	"april" boolean DEFAULT true,
	"may" boolean DEFAULT true,
	"june" boolean DEFAULT true,
	"july" boolean DEFAULT true,
	"august" boolean DEFAULT true,
	"september" boolean DEFAULT true,
	"october" boolean DEFAULT true,
	"november" boolean DEFAULT true,
	"december" boolean DEFAULT true,
	"valid_from" timestamp
);
--> statement-breakpoint
CREATE TABLE "contracts" (
	"id" serial PRIMARY KEY NOT NULL,
	"data_set_id" integer NOT NULL,
	"group_id" integer,
	"supplier" text,
	"reference_number" text,
	"type" text,
	"date_start" timestamp,
	"date_end" timestamp,
	"kva" real,
	"maximum_input_capacity" real,
	"climate_change_levy" real,
	"fossil_fuel_levy" real,
	"rate_units" real,
	"rate_units_1_split" real,
	"rate_fixed" real,
	"rate_fixed_per_day" boolean DEFAULT false,
	"rate_kva" real,
	"rate_kva_2" real,
	"rate_kva_per_day" boolean DEFAULT false,
	"rate_kva_split" real,
	"rate_md" real,
	"rate_md_2" real,
	"rate_md_split" real,
	"rate_transportation" real,
	"rate_transportation_per_kwh" boolean DEFAULT false,
	"rate_metering" real,
	"rate_metering_per_day" boolean DEFAULT false,
	"rate_settlements" real,
	"rate_settlements_per_day" boolean DEFAULT false,
	"rate_triad" real,
	"rate_green" real,
	"rate_green_percent" real,
	"rate_fit" real,
	"rate_roc" real,
	"kwh_split_1" real,
	"kwh_split_1_cost_rate" real,
	"kwh_split_2" real,
	"kwh_split_2_cost_rate" real,
	"kwh_split_3" real,
	"kwh_split_3_cost_rate" real,
	"kwh_split_4" real,
	"kwh_split_4_cost_rate" real,
	"kwh_split_5" real,
	"kwh_split_5_cost_rate" real,
	"kwh_split_6" real,
	"kwh_split_6_cost_rate" real,
	"reactive_power_1_rate" real,
	"reactive_power_1_split" real,
	"reactive_power_2_rate" real,
	"reactive_power_2_split" real,
	"kvarh_default" real,
	"vat_1_rate" real,
	"vat_2_rate" real,
	"vat_split" real,
	"loss_adjustment" boolean DEFAULT false,
	"tuos" boolean DEFAULT false,
	"use_of_system" boolean DEFAULT false,
	"use_distributor_capacity" boolean DEFAULT false,
	"use_distributor_reactive_power" boolean DEFAULT false,
	"bank_holidays" integer,
	"billing_point" integer,
	"clock" boolean DEFAULT false,
	"batch" integer
);
--> statement-breakpoint
CREATE TABLE "data_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"data_set_id" integer NOT NULL,
	"type" integer DEFAULT 0,
	"date" timestamp NOT NULL,
	"day_total" real,
	"i0030" real,
	"i0100" real,
	"i0130" real,
	"i0200" real,
	"i0230" real,
	"i0300" real,
	"i0330" real,
	"i0400" real,
	"i0430" real,
	"i0500" real,
	"i0530" real,
	"i0600" real,
	"i0630" real,
	"i0700" real,
	"i0730" real,
	"i0800" real,
	"i0830" real,
	"i0900" real,
	"i0930" real,
	"i1000" real,
	"i1030" real,
	"i1100" real,
	"i1130" real,
	"i1200" real,
	"i1230" real,
	"i1300" real,
	"i1330" real,
	"i1400" real,
	"i1430" real,
	"i1500" real,
	"i1530" real,
	"i1600" real,
	"i1630" real,
	"i1700" real,
	"i1730" real,
	"i1800" real,
	"i1830" real,
	"i1900" real,
	"i1930" real,
	"i2000" real,
	"i2030" real,
	"i2100" real,
	"i2130" real,
	"i2200" real,
	"i2230" real,
	"i2300" real,
	"i2330" real,
	"i2400" real,
	"f0030" integer,
	"f0100" integer,
	"f0130" integer,
	"f0200" integer,
	"f0230" integer,
	"f0300" integer,
	"f0330" integer,
	"f0400" integer,
	"f0430" integer,
	"f0500" integer,
	"f0530" integer,
	"f0600" integer,
	"f0630" integer,
	"f0700" integer,
	"f0730" integer,
	"f0800" integer,
	"f0830" integer,
	"f0900" integer,
	"f0930" integer,
	"f1000" integer,
	"f1030" integer,
	"f1100" integer,
	"f1130" integer,
	"f1200" integer,
	"f1230" integer,
	"f1300" integer,
	"f1330" integer,
	"f1400" integer,
	"f1430" integer,
	"f1500" integer,
	"f1530" integer,
	"f1600" integer,
	"f1630" integer,
	"f1700" integer,
	"f1730" integer,
	"f1800" integer,
	"f1830" integer,
	"f1900" integer,
	"f1930" integer,
	"f2000" integer,
	"f2030" integer,
	"f2100" integer,
	"f2130" integer,
	"f2200" integer,
	"f2230" integer,
	"f2300" integer,
	"f2330" integer,
	"f2400" integer
);
--> statement-breakpoint
CREATE TABLE "data_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"data_set_id" integer NOT NULL,
	"utility_type" text NOT NULL,
	"date" timestamp NOT NULL,
	"previous_date" timestamp,
	"direct" text,
	"estimate" text,
	"units" real,
	"cost" real,
	"batch" integer,
	"standing_charge" real,
	"other_charge" real,
	"vat" real,
	"ccl" real,
	"ccl_rate" real,
	"invoice_number" text,
	"supplier_name" text,
	"number" text,
	"locked" integer,
	"passed_to_accounts" integer,
	"status" integer,
	"date_paid" timestamp,
	"date_tax_point" timestamp,
	"exclude_from_reports" integer,
	"last_update" timestamp,
	"last_user" text,
	"note" text,
	"m1_present" real,
	"m1_previous" real,
	"m1_factor" real,
	"m1_units" real,
	"m1_cost_rate" real,
	"m1_cost" real,
	"m2_present" real,
	"m2_previous" real,
	"m2_factor" real,
	"m2_units" real,
	"m2_cost_rate" real,
	"m2_cost" real,
	"m3_present" real,
	"m3_previous" real,
	"m3_factor" real,
	"m3_units" real,
	"m3_cost_rate" real,
	"m3_cost" real,
	"m4_present" real,
	"m4_previous" real,
	"m4_factor" real,
	"m4_units" real,
	"m4_cost_rate" real,
	"m4_cost" real,
	"vat_split" real,
	"vat_1_percent" real,
	"vat_1" real,
	"vat_2_percent" real,
	"vat_2" real,
	"standing_charge_rate" real,
	"de_minimis" real,
	"de_minimis_threshold" real,
	"non_vatable_charges" real,
	"flexible_purchasing" real,
	"misc_cost" real,
	"m5_present" real,
	"m5_previous" real,
	"m5_factor" real,
	"m5_units" real,
	"m5_cost_rate" real,
	"m5_cost" real,
	"m6_present" real,
	"m6_previous" real,
	"m6_factor" real,
	"m6_units" real,
	"m6_cost_rate" real,
	"m6_cost" real,
	"m7_present" real,
	"m7_previous" real,
	"m7_factor" real,
	"m7_units" real,
	"m7_cost_rate" real,
	"m7_cost" real,
	"m8_present" real,
	"m8_previous" real,
	"m8_factor" real,
	"m8_units" real,
	"m8_cost_rate" real,
	"m8_cost" real,
	"m1_split1" real,
	"m1_split1_cost_rate" real,
	"m1_split1_cost" real,
	"m1_split2" real,
	"m1_split2_cost_rate" real,
	"m1_split2_cost" real,
	"m1_split3" real,
	"m1_split3_cost_rate" real,
	"m1_split3_cost" real,
	"m1_split4" real,
	"m1_split4_cost_rate" real,
	"m1_split4_cost" real,
	"m1_split5" real,
	"m1_split5_cost_rate" real,
	"m1_split5_cost" real,
	"m1_split6" real,
	"m1_split6_cost_rate" real,
	"m1_split6_cost" real,
	"kv" real,
	"kv_cost_rate" real,
	"kv_cost" real,
	"kva" real,
	"kva_cost_rate" real,
	"kva_cost" real,
	"kv_factor" real,
	"kva_factor" real,
	"kv_split1" real,
	"kv_split1_cost_rate" real,
	"kv_split1_cost" real,
	"kva_split1" real,
	"kva_split1_cost_rate" real,
	"kva_split1_cost" real,
	"fuel_adjustment_cost" real,
	"fuel_adjustment_percent" real,
	"power_factor" real,
	"reactive_power" real,
	"reactive_power_cost_rate" real,
	"reactive_power_cost" real,
	"reactive_power_factor" real,
	"reactive_power_2_factor" real,
	"reactive_power_2_cost" real,
	"reactive_power_2_cost_rate" real,
	"green_charge" real,
	"green_charge_rate" real,
	"green_percent" real,
	"settlements" real,
	"settlements_rate" real,
	"tuos" real,
	"duos" real,
	"triad" real,
	"roc" real,
	"roc_rate" real,
	"feed_in_cost" real,
	"feed_in_cost_rate" real,
	"duos_green_units" real,
	"duos_green_cost_rate" real,
	"duos_green_cost" real,
	"duos_amber_units" real,
	"duos_amber_cost_rate" real,
	"duos_amber_cost" real,
	"duos_red_units" real,
	"duos_red_cost_rate" real,
	"duos_red_cost" real,
	"kwh_factor" real,
	"transportation" real,
	"metering" real,
	"standing_charge_2" real,
	"standing_charge_rate_2" real,
	"water_factor" real,
	"water_units" real,
	"water_cost_rate" real,
	"water_cost" real,
	"sewerage_factor" real,
	"sewerage_units" real,
	"sewerage_cost_rate" real,
	"sewerage_cost" real,
	"rates" real,
	"rates_cost_rate" real,
	"rates_cost" real,
	"trade_effluent_cost" real,
	"surface_water_cost" real,
	"environmental_cost" real,
	"highway_cost" real,
	"volume_cost" real,
	"tariff_cost" real
);
--> statement-breakpoint
CREATE TABLE "data_sets" (
	"id" serial PRIMARY KEY NOT NULL,
	"site_id" integer NOT NULL,
	"name" text,
	"utility_type_id" integer NOT NULL,
	"mpan_profile" text,
	"mpan_core_mprn" text,
	"mpan_core_mprn_2" text,
	"mpan_core_mprn_3" text,
	"mpan_core_mprn_4" text,
	"meter_serial_1" text,
	"location" text,
	"supplier_id" integer,
	"tariff_name" text,
	"meter_type" text,
	"is_virtual" boolean DEFAULT false,
	"date_closed" timestamp,
	"is_active" boolean DEFAULT true,
	"last_update" timestamp DEFAULT now(),
	"code" text,
	"code2" text,
	"host_supplier" text,
	"bill_frequency" text,
	"annual_quantity" real,
	"meter_digits" integer,
	"meter_number" text,
	"other_number" text,
	"sub_meter" boolean DEFAULT false,
	"aggregate_meter" boolean DEFAULT false,
	"landlord_billed" boolean DEFAULT false,
	"interruptible" boolean DEFAULT false,
	"vat_rate" real,
	"tariff_ccl_rate" real,
	"comments" text,
	"units" text,
	"kva" real,
	"voltage" text,
	"power_factor" real,
	"eac" real,
	"profile_meter" boolean DEFAULT false,
	"profile_frequency" text,
	"profile_scale_factor" real,
	"profile_kwh_factor" real,
	"profile_calorific_value" real,
	"profile_correction_factor" real,
	"profile_cost_rate" integer,
	"profile_meter_max" integer,
	"profile_threshold_1" real,
	"profile_threshold_2" real,
	"meter_operator" text,
	"meter_asset_manager" text,
	"mhhs_applied" boolean DEFAULT false,
	"rota_disconnection_alpha_id" text,
	"gas_meter_size" text,
	"nominated_soq" real,
	"soq_peak" real,
	"soq_alternative" real,
	"soq_minimum" real,
	"supply_hourly_quantity" real,
	"kwh_factor" real,
	"meter_size" real,
	"meter_size_2" real,
	"meter_type_capacity" real,
	"return_to_sewer" real,
	"highway_drainage" boolean DEFAULT false,
	"surface_water" boolean DEFAULT false,
	"sewerage_supplier" text,
	"water_supplier" text,
	"sewerage_wholesale_tariff" text,
	"water_wholesale_tariff" text
);
--> statement-breakpoint
CREATE TABLE "groups" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "groups_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "import_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"filename" text NOT NULL,
	"format" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"total_rows" integer DEFAULT 0,
	"imported_rows" integer DEFAULT 0,
	"skipped_rows" integer DEFAULT 0,
	"error_rows" integer DEFAULT 0,
	"error_details" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "site_groups" (
	"id" serial PRIMARY KEY NOT NULL,
	"site_id" integer NOT NULL,
	"group_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "config_site_status" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "config_site_status_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "sites" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"code" text,
	"address" text,
	"address2" text,
	"town" text,
	"county" text,
	"postcode" text,
	"latitude" double precision,
	"longitude" double precision,
	"telephone" text,
	"email" text,
	"status_id" integer,
	"photo_url" text,
	"comments" text,
	"floor_area" numeric(12, 2),
	"degree_day_area" text,
	"last_update" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "config_suppliers" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"utility" text,
	"address_1" text,
	"address_2" text,
	"town" text,
	"county" text,
	"post_code" text,
	"telephone" text,
	"fax" text,
	"emergency_telephone" text,
	"notes" text,
	"code" text,
	"email_1" text,
	"email_2" text,
	"is_active" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "todo_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"text" text NOT NULL,
	"is_done" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	"role" text DEFAULT 'user' NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "config_utilities" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"code" text,
	"standard_units" text,
	CONSTRAINT "config_utilities_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "charge_items" ADD CONSTRAINT "charge_items_data_set_id_data_sets_id_fk" FOREIGN KEY ("data_set_id") REFERENCES "public"."data_sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "charge_items" ADD CONSTRAINT "charge_items_charge_type_id_config_charge_types_id_fk" FOREIGN KEY ("charge_type_id") REFERENCES "public"."config_charge_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contract_charges" ADD CONSTRAINT "contract_charges_contract_id_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."contracts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contract_charges" ADD CONSTRAINT "contract_charges_charge_type_id_config_charge_types_id_fk" FOREIGN KEY ("charge_type_id") REFERENCES "public"."config_charge_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contract_data" ADD CONSTRAINT "contract_data_contract_id_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."contracts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_data_set_id_data_sets_id_fk" FOREIGN KEY ("data_set_id") REFERENCES "public"."data_sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "data_profiles" ADD CONSTRAINT "data_profiles_data_set_id_data_sets_id_fk" FOREIGN KEY ("data_set_id") REFERENCES "public"."data_sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "data_records" ADD CONSTRAINT "data_records_data_set_id_data_sets_id_fk" FOREIGN KEY ("data_set_id") REFERENCES "public"."data_sets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "data_sets" ADD CONSTRAINT "data_sets_site_id_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "data_sets" ADD CONSTRAINT "data_sets_utility_type_id_config_utilities_id_fk" FOREIGN KEY ("utility_type_id") REFERENCES "public"."config_utilities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "data_sets" ADD CONSTRAINT "data_sets_supplier_id_config_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."config_suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_groups" ADD CONSTRAINT "site_groups_site_id_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_groups" ADD CONSTRAINT "site_groups_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sites" ADD CONSTRAINT "sites_status_id_config_site_status_id_fk" FOREIGN KEY ("status_id") REFERENCES "public"."config_site_status"("id") ON DELETE no action ON UPDATE no action;