import { pgTable, text, serial, integer, timestamp, decimal, boolean, doublePrecision, real } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// --- Configuration / Lookup Tables ---

export const siteStatus = pgTable("config_site_status", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(), // e.g., Active, Closed, Inactive
});

export const utilities = pgTable("config_utilities", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(), // Electricity, Gas, Water, etc.
  code: text("code"),
  standardUnits: text("standard_units"),
});

export const suppliers = pgTable("config_suppliers", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  utility: text("utility"),
  address1: text("address_1"),
  address2: text("address_2"),
  town: text("town"),
  county: text("county"),
  postCode: text("post_code"),
  telephone: text("telephone"),
  fax: text("fax"),
  emergencyTelephone: text("emergency_telephone"),
  notes: text("notes"),
  code: text("code"),
  email1: text("email_1"),
  email2: text("email_2"),
  isActive: boolean("is_active").default(true),
});

// --- Core Entities ---

export const sites = pgTable("sites", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  code: text("code"), // UPRN
  address: text("address"),
  address2: text("address2"),
  town: text("town"),
  county: text("county"),
  postcode: text("postcode"),
  latitude: doublePrecision("latitude"),
  longitude: doublePrecision("longitude"),
  telephone: text("telephone"),
  email: text("email"),
  statusId: integer("status_id").references(() => siteStatus.id),
  photoUrl: text("photo_url"),
  comments: text("comments"),
  floorArea: decimal("floor_area", { precision: 12, scale: 2 }),
  degreeDayArea: text("degree_day_area"),
  lastUpdate: timestamp("last_update").defaultNow(),
});

export const groups = pgTable("groups", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
});

export const siteGroups = pgTable("site_groups", {
  id: serial("id").primaryKey(),
  siteId: integer("site_id").references(() => sites.id).notNull(),
  groupId: integer("group_id").references(() => groups.id).notNull(),
});

export const dataSets = pgTable("data_sets", {
  id: serial("id").primaryKey(),
  siteId: integer("site_id").references(() => sites.id).notNull(),
  name: text("name"),
  utilityTypeId: integer("utility_type_id").references(() => utilities.id).notNull(),
  mpanProfile: text("mpan_profile"),
  mpanCoreMprn: text("mpan_core_mprn"),
  mpanCoreMprn2: text("mpan_core_mprn_2"),
  mpanCoreMprn3: text("mpan_core_mprn_3"),
  mpanCoreMprn4: text("mpan_core_mprn_4"),
  meterSerial1: text("meter_serial_1"),
  location: text("location"),
  supplierId: integer("supplier_id").references(() => suppliers.id),
  tariffName: text("tariff_name"),
  meterType: text("meter_type"),
  isVirtual: boolean("is_virtual").default(false),
  dateClosed: timestamp("date_closed"),
  isActive: boolean("is_active").default(true),
  lastUpdate: timestamp("last_update").defaultNow(),
  code: text("code"),
  code2: text("code2"),
  hostSupplier: text("host_supplier"),
  billFrequency: text("bill_frequency"),
  annualQuantity: real("annual_quantity"),
  meterDigits: integer("meter_digits"),
  meterNumber: text("meter_number"),
  otherNumber: text("other_number"),
  subMeter: boolean("sub_meter").default(false),
  aggregateMeter: boolean("aggregate_meter").default(false),
  landlordBilled: boolean("landlord_billed").default(false),
  interruptible: boolean("interruptible").default(false),
  vatRate: real("vat_rate"),
  tariffCclRate: real("tariff_ccl_rate"),
  comments: text("comments"),
  units: text("units"),
  kva: real("kva"),
  voltage: text("voltage"),
  powerFactor: real("power_factor"),
  eac: real("eac"),
  profileMeter: boolean("profile_meter").default(false),
  profileFrequency: text("profile_frequency"),
  profileScaleFactor: real("profile_scale_factor"),
  profileKwhFactor: real("profile_kwh_factor"),
  profileCalorificValue: real("profile_calorific_value"),
  profileCorrectionFactor: real("profile_correction_factor"),
  profileCostRate: integer("profile_cost_rate"),
  profileMeterMax: integer("profile_meter_max"),
  profileThreshold1: real("profile_threshold_1"),
  profileThreshold2: real("profile_threshold_2"),
  meterOperator: text("meter_operator"),
  meterAssetManager: text("meter_asset_manager"),
  mhhsApplied: boolean("mhhs_applied").default(false),
  rotaDisconnectionAlphaId: text("rota_disconnection_alpha_id"),
  gasMeterSize: text("gas_meter_size"),
  nominatedSoq: real("nominated_soq"),
  soqPeak: real("soq_peak"),
  soqAlternative: real("soq_alternative"),
  soqMinimum: real("soq_minimum"),
  supplyHourlyQuantity: real("supply_hourly_quantity"),
  kwhFactor: real("kwh_factor"),
  meterSize: real("meter_size"),
  meterSize2: real("meter_size_2"),
  meterTypeCapacity: real("meter_type_capacity"),
  returnToSewer: real("return_to_sewer"),
  highwayDrainage: boolean("highway_drainage").default(false),
  surfaceWater: boolean("surface_water").default(false),
  sewerageSupplier: text("sewerage_supplier"),
  waterSupplier: text("water_supplier"),
  sewerageWholesaleTariff: text("sewerage_wholesale_tariff"),
  waterWholesaleTariff: text("water_wholesale_tariff"),
});

// --- Contracts ---

export const contracts = pgTable("contracts", {
  id: serial("id").primaryKey(),
  dataSetId: integer("data_set_id").references(() => dataSets.id).notNull(),
  groupId: integer("group_id").references(() => groups.id),
  supplier: text("supplier"),
  referenceNumber: text("reference_number"),
  type: text("type"),
  dateStart: timestamp("date_start"),
  dateEnd: timestamp("date_end"),
  kva: real("kva"),
  maximumInputCapacity: real("maximum_input_capacity"),
  climateChangeLevy: real("climate_change_levy"),
  fossilFuelLevy: real("fossil_fuel_levy"),
  rateUnits: real("rate_units"),
  rateUnits1Split: real("rate_units_1_split"),
  rateFixed: real("rate_fixed"),
  rateFixedPerDay: boolean("rate_fixed_per_day").default(false),
  rateKva: real("rate_kva"),
  rateKva2: real("rate_kva_2"),
  rateKvaPerDay: boolean("rate_kva_per_day").default(false),
  rateKvaSplit: real("rate_kva_split"),
  rateMd: real("rate_md"),
  rateMd2: real("rate_md_2"),
  rateMdSplit: real("rate_md_split"),
  rateTransportation: real("rate_transportation"),
  rateTransportationPerKwh: boolean("rate_transportation_per_kwh").default(false),
  rateMetering: real("rate_metering"),
  rateMeteringPerDay: boolean("rate_metering_per_day").default(false),
  rateSettlements: real("rate_settlements"),
  rateSettlementsPerDay: boolean("rate_settlements_per_day").default(false),
  rateTriad: real("rate_triad"),
  rateGreen: real("rate_green"),
  rateGreenPercent: real("rate_green_percent"),
  rateFit: real("rate_fit"),
  rateRoc: real("rate_roc"),
  kwhSplit1: real("kwh_split_1"),
  kwhSplit1CostRate: real("kwh_split_1_cost_rate"),
  kwhSplit2: real("kwh_split_2"),
  kwhSplit2CostRate: real("kwh_split_2_cost_rate"),
  kwhSplit3: real("kwh_split_3"),
  kwhSplit3CostRate: real("kwh_split_3_cost_rate"),
  kwhSplit4: real("kwh_split_4"),
  kwhSplit4CostRate: real("kwh_split_4_cost_rate"),
  kwhSplit5: real("kwh_split_5"),
  kwhSplit5CostRate: real("kwh_split_5_cost_rate"),
  kwhSplit6: real("kwh_split_6"),
  kwhSplit6CostRate: real("kwh_split_6_cost_rate"),
  reactivePower1Rate: real("reactive_power_1_rate"),
  reactivePower1Split: real("reactive_power_1_split"),
  reactivePower2Rate: real("reactive_power_2_rate"),
  reactivePower2Split: real("reactive_power_2_split"),
  kvarhDefault: real("kvarh_default"),
  vat1Rate: real("vat_1_rate"),
  vat2Rate: real("vat_2_rate"),
  vatSplit: real("vat_split"),
  lossAdjustment: boolean("loss_adjustment").default(false),
  tuos: boolean("tuos").default(false),
  useOfSystem: boolean("use_of_system").default(false),
  useDistributorCapacity: boolean("use_distributor_capacity").default(false),
  useDistributorReactivePower: boolean("use_distributor_reactive_power").default(false),
  bankHolidays: integer("bank_holidays"),
  billingPoint: integer("billing_point"),
  clock: boolean("clock").default(false),
  batch: integer("batch"),
});

export const chargeTypes = pgTable("config_charge_types", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
});

export const contractCharges = pgTable("contract_charges", {
  id: serial("id").primaryKey(),
  contractId: integer("contract_id").references(() => contracts.id).notNull(),
  chargeTypeId: integer("charge_type_id").references(() => chargeTypes.id),
  rate: real("rate"),
  tolerance: real("tolerance"),
  toleranceRate: real("tolerance_rate"),
  toleranceUnits: real("tolerance_units"),
});

export const contractData = pgTable("contract_data", {
  id: serial("id").primaryKey(),
  contractId: integer("contract_id").references(() => contracts.id).notNull(),
  type: text("type"),
  costRate: real("cost_rate"),
  timeStart: text("time_start"),
  timeFinish: text("time_finish"),
  meter: integer("meter"),
  description: text("description"),
  sunday: boolean("sunday").default(true),
  monday: boolean("monday").default(true),
  tuesday: boolean("tuesday").default(true),
  wednesday: boolean("wednesday").default(true),
  thursday: boolean("thursday").default(true),
  friday: boolean("friday").default(true),
  saturday: boolean("saturday").default(true),
  january: boolean("january").default(true),
  february: boolean("february").default(true),
  march: boolean("march").default(true),
  april: boolean("april").default(true),
  may: boolean("may").default(true),
  june: boolean("june").default(true),
  july: boolean("july").default(true),
  august: boolean("august").default(true),
  september: boolean("september").default(true),
  october: boolean("october").default(true),
  november: boolean("november").default(true),
  december: boolean("december").default(true),
  validFrom: timestamp("valid_from"),
});

export const chargeItems = pgTable("charge_items", {
  id: serial("id").primaryKey(),
  dataSetId: integer("data_set_id").references(() => dataSets.id).notNull(),
  dataRecordId: integer("data_record_id"),
  chargeTypeId: integer("charge_type_id").references(() => chargeTypes.id),
  cost: real("cost"),
  units: real("units"),
  rate: real("rate"),
});

// --- Data Tables ---

export const dataRecords = pgTable("data_records", {
  id: serial("id").primaryKey(),
  dataSetId: integer("data_set_id").references(() => dataSets.id).notNull(),
  utilityType: text("utility_type").notNull(),
  date: timestamp("date").notNull(),
  previousDate: timestamp("previous_date"),
  direct: text("direct"),
  estimate: text("estimate"),
  units: real("units"),
  cost: real("cost"),
  batch: integer("batch"),
  standingCharge: real("standing_charge"),
  otherCharge: real("other_charge"),
  vat: real("vat"),
  ccl: real("ccl"),
  cclRate: real("ccl_rate"),
  invoiceNumber: text("invoice_number"),
  supplierName: text("supplier_name"),
  number: text("number"),
  locked: integer("locked"),
  passedToAccounts: integer("passed_to_accounts"),
  status: integer("status"),
  datePaid: timestamp("date_paid"),
  dateTaxPoint: timestamp("date_tax_point"),
  excludeFromReports: integer("exclude_from_reports"),
  lastUpdate: timestamp("last_update"),
  lastUser: text("last_user"),
  note: text("note"),

  m1Present: real("m1_present"),
  m1Previous: real("m1_previous"),
  m1Factor: real("m1_factor"),
  m1Units: real("m1_units"),
  m1CostRate: real("m1_cost_rate"),
  m1Cost: real("m1_cost"),
  m2Present: real("m2_present"),
  m2Previous: real("m2_previous"),
  m2Factor: real("m2_factor"),
  m2Units: real("m2_units"),
  m2CostRate: real("m2_cost_rate"),
  m2Cost: real("m2_cost"),
  m3Present: real("m3_present"),
  m3Previous: real("m3_previous"),
  m3Factor: real("m3_factor"),
  m3Units: real("m3_units"),
  m3CostRate: real("m3_cost_rate"),
  m3Cost: real("m3_cost"),
  m4Present: real("m4_present"),
  m4Previous: real("m4_previous"),
  m4Factor: real("m4_factor"),
  m4Units: real("m4_units"),
  m4CostRate: real("m4_cost_rate"),
  m4Cost: real("m4_cost"),

  vatSplit: real("vat_split"),
  vat1Percent: real("vat_1_percent"),
  vat1: real("vat_1"),
  vat2Percent: real("vat_2_percent"),
  vat2: real("vat_2"),
  standingChargeRate: real("standing_charge_rate"),
  deMinimis: real("de_minimis"),
  deMinimisThreshold: real("de_minimis_threshold"),
  nonVatableCharges: real("non_vatable_charges"),
  flexiblePurchasing: real("flexible_purchasing"),
  miscCost: real("misc_cost"),

  m5Present: real("m5_present"),
  m5Previous: real("m5_previous"),
  m5Factor: real("m5_factor"),
  m5Units: real("m5_units"),
  m5CostRate: real("m5_cost_rate"),
  m5Cost: real("m5_cost"),
  m6Present: real("m6_present"),
  m6Previous: real("m6_previous"),
  m6Factor: real("m6_factor"),
  m6Units: real("m6_units"),
  m6CostRate: real("m6_cost_rate"),
  m6Cost: real("m6_cost"),
  m7Present: real("m7_present"),
  m7Previous: real("m7_previous"),
  m7Factor: real("m7_factor"),
  m7Units: real("m7_units"),
  m7CostRate: real("m7_cost_rate"),
  m7Cost: real("m7_cost"),
  m8Present: real("m8_present"),
  m8Previous: real("m8_previous"),
  m8Factor: real("m8_factor"),
  m8Units: real("m8_units"),
  m8CostRate: real("m8_cost_rate"),
  m8Cost: real("m8_cost"),
  m1Split1: real("m1_split1"),
  m1Split1CostRate: real("m1_split1_cost_rate"),
  m1Split1Cost: real("m1_split1_cost"),
  m1Split2: real("m1_split2"),
  m1Split2CostRate: real("m1_split2_cost_rate"),
  m1Split2Cost: real("m1_split2_cost"),
  m1Split3: real("m1_split3"),
  m1Split3CostRate: real("m1_split3_cost_rate"),
  m1Split3Cost: real("m1_split3_cost"),
  m1Split4: real("m1_split4"),
  m1Split4CostRate: real("m1_split4_cost_rate"),
  m1Split4Cost: real("m1_split4_cost"),
  m1Split5: real("m1_split5"),
  m1Split5CostRate: real("m1_split5_cost_rate"),
  m1Split5Cost: real("m1_split5_cost"),
  m1Split6: real("m1_split6"),
  m1Split6CostRate: real("m1_split6_cost_rate"),
  m1Split6Cost: real("m1_split6_cost"),

  kv: real("kv"),
  kvCostRate: real("kv_cost_rate"),
  kvCost: real("kv_cost"),
  kva: real("kva"),
  kvaCostRate: real("kva_cost_rate"),
  kvaCost: real("kva_cost"),
  kvFactor: real("kv_factor"),
  kvaFactor: real("kva_factor"),
  kvSplit1: real("kv_split1"),
  kvSplit1CostRate: real("kv_split1_cost_rate"),
  kvSplit1Cost: real("kv_split1_cost"),
  kvaSplit1: real("kva_split1"),
  kvaSplit1CostRate: real("kva_split1_cost_rate"),
  kvaSplit1Cost: real("kva_split1_cost"),
  fuelAdjustmentCost: real("fuel_adjustment_cost"),
  fuelAdjustmentPercent: real("fuel_adjustment_percent"),
  powerFactor: real("power_factor"),
  reactivePower: real("reactive_power"),
  reactivePowerCostRate: real("reactive_power_cost_rate"),
  reactivePowerCost: real("reactive_power_cost"),
  reactivePowerFactor: real("reactive_power_factor"),
  reactivePower2Factor: real("reactive_power_2_factor"),
  reactivePower2Cost: real("reactive_power_2_cost"),
  reactivePower2CostRate: real("reactive_power_2_cost_rate"),
  greenCharge: real("green_charge"),
  greenChargeRate: real("green_charge_rate"),
  greenPercent: real("green_percent"),
  settlements: real("settlements"),
  settlementsRate: real("settlements_rate"),
  tuos: real("tuos"),
  duos: real("duos"),
  triad: real("triad"),
  roc: real("roc"),
  rocRate: real("roc_rate"),
  feedInCost: real("feed_in_cost"),
  feedInCostRate: real("feed_in_cost_rate"),
  duosGreenUnits: real("duos_green_units"),
  duosGreenCostRate: real("duos_green_cost_rate"),
  duosGreenCost: real("duos_green_cost"),
  duosAmberUnits: real("duos_amber_units"),
  duosAmberCostRate: real("duos_amber_cost_rate"),
  duosAmberCost: real("duos_amber_cost"),
  duosRedUnits: real("duos_red_units"),
  duosRedCostRate: real("duos_red_cost_rate"),
  duosRedCost: real("duos_red_cost"),

  kwhFactor: real("kwh_factor"),
  transportation: real("transportation"),
  metering: real("metering"),

  standingCharge2: real("standing_charge_2"),
  standingChargeRate2: real("standing_charge_rate_2"),
  waterFactor: real("water_factor"),
  waterUnits: real("water_units"),
  waterCostRate: real("water_cost_rate"),
  waterCost: real("water_cost"),
  sewerageFactor: real("sewerage_factor"),
  sewerageUnits: real("sewerage_units"),
  sewerageCostRate: real("sewerage_cost_rate"),
  sewerageCost: real("sewerage_cost"),
  rates: real("rates"),
  ratesCostRate: real("rates_cost_rate"),
  ratesCost: real("rates_cost"),
  tradeEffluentCost: real("trade_effluent_cost"),
  surfaceWaterCost: real("surface_water_cost"),
  environmentalCost: real("environmental_cost"),
  highwayCost: real("highway_cost"),
  volumeCost: real("volume_cost"),
  tariffCost: real("tariff_cost"),
});

export const dataProfiles = pgTable("data_profiles", {
  id: serial("id").primaryKey(),
  dataSetId: integer("data_set_id").references(() => dataSets.id).notNull(),
  type: integer("type").default(0),
  date: timestamp("date").notNull(),
  dayTotal: real("day_total"),
  i0030: real("i0030"), i0100: real("i0100"), i0130: real("i0130"), i0200: real("i0200"),
  i0230: real("i0230"), i0300: real("i0300"), i0330: real("i0330"), i0400: real("i0400"),
  i0430: real("i0430"), i0500: real("i0500"), i0530: real("i0530"), i0600: real("i0600"),
  i0630: real("i0630"), i0700: real("i0700"), i0730: real("i0730"), i0800: real("i0800"),
  i0830: real("i0830"), i0900: real("i0900"), i0930: real("i0930"), i1000: real("i1000"),
  i1030: real("i1030"), i1100: real("i1100"), i1130: real("i1130"), i1200: real("i1200"),
  i1230: real("i1230"), i1300: real("i1300"), i1330: real("i1330"), i1400: real("i1400"),
  i1430: real("i1430"), i1500: real("i1500"), i1530: real("i1530"), i1600: real("i1600"),
  i1630: real("i1630"), i1700: real("i1700"), i1730: real("i1730"), i1800: real("i1800"),
  i1830: real("i1830"), i1900: real("i1900"), i1930: real("i1930"), i2000: real("i2000"),
  i2030: real("i2030"), i2100: real("i2100"), i2130: real("i2130"), i2200: real("i2200"),
  i2230: real("i2230"), i2300: real("i2300"), i2330: real("i2330"), i2400: real("i2400"),
  f0030: integer("f0030"), f0100: integer("f0100"), f0130: integer("f0130"), f0200: integer("f0200"),
  f0230: integer("f0230"), f0300: integer("f0300"), f0330: integer("f0330"), f0400: integer("f0400"),
  f0430: integer("f0430"), f0500: integer("f0500"), f0530: integer("f0530"), f0600: integer("f0600"),
  f0630: integer("f0630"), f0700: integer("f0700"), f0730: integer("f0730"), f0800: integer("f0800"),
  f0830: integer("f0830"), f0900: integer("f0900"), f0930: integer("f0930"), f1000: integer("f1000"),
  f1030: integer("f1030"), f1100: integer("f1100"), f1130: integer("f1130"), f1200: integer("f1200"),
  f1230: integer("f1230"), f1300: integer("f1300"), f1330: integer("f1330"), f1400: integer("f1400"),
  f1430: integer("f1430"), f1500: integer("f1500"), f1530: integer("f1530"), f1600: integer("f1600"),
  f1630: integer("f1630"), f1700: integer("f1700"), f1730: integer("f1730"), f1800: integer("f1800"),
  f1830: integer("f1830"), f1900: integer("f1900"), f1930: integer("f1930"), f2000: integer("f2000"),
  f2030: integer("f2030"), f2100: integer("f2100"), f2130: integer("f2130"), f2200: integer("f2200"),
  f2230: integer("f2230"), f2300: integer("f2300"), f2330: integer("f2330"), f2400: integer("f2400"),
});

// --- Admin To Do ---

export const todoItems = pgTable("todo_items", {
  id: serial("id").primaryKey(),
  text: text("text").notNull(),
  isDone: boolean("is_done").default(false).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// --- Auth ---

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  role: text("role").default("user").notNull(),
});

// --- Schemas ---

export const insertSiteSchema = createInsertSchema(sites).omit({ id: true, lastUpdate: true });
export const insertDataSetSchema = createInsertSchema(dataSets).omit({ id: true, lastUpdate: true });
export const insertDataRecordSchema = createInsertSchema(dataRecords).omit({ id: true });
export const insertContractSchema = createInsertSchema(contracts).omit({ id: true });
export const insertContractChargeSchema = createInsertSchema(contractCharges).omit({ id: true });
export const insertUserSchema = createInsertSchema(users).omit({ id: true });

export const insertTodoSchema = createInsertSchema(todoItems).omit({ id: true, createdAt: true });

// --- Types ---

export type Site = typeof sites.$inferSelect;
export type DataSet = typeof dataSets.$inferSelect;
export type DataRecord = typeof dataRecords.$inferSelect;
export type Contract = typeof contracts.$inferSelect;
export type ContractCharge = typeof contractCharges.$inferSelect;
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type Group = typeof groups.$inferSelect;
export type InsertContract = z.infer<typeof insertContractSchema>;
export type InsertContractCharge = z.infer<typeof insertContractChargeSchema>;
export type ChargeType = typeof chargeTypes.$inferSelect;
export type TodoItem = typeof todoItems.$inferSelect;
export type InsertTodo = z.infer<typeof insertTodoSchema>;
